{
    'name': 'Stock Reservation',
    'summary': 'Stock reservations on products',
    'version': '12.0.0.1',
    'author': "Camptocamp,Odoo Community Association (OCA)",
    'category': 'Warehouse',
    'license': 'AGPL-3',
    'complexity': 'normal',
    'images': [],
    'website': "http://www.camptocamp.com",
    'depends': ['stock'],
    'demo': [],
    'data': ['view/stock_reserve.xml',
             'view/product.xml',
             'data/stock_data.xml',
             'security/ir.model.access.csv',
             ],
    'auto_install': False,
    'installable': True,
}
